#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d 爵      

bspc config ignore_ewmh_struts 	true
bspc config top_padding		40
bspc config bottom_padding	2
bspc config border_width         0
bspc config window_gap          34
bspc config border_radius	10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

~/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr & 
picom -b --config ~/.config/picom/picom.conf &
feh --bg-fill ~/Pictures/landscape.png &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
